apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kiri-tech-tls
spec:
  secretName: kiri-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kiri.tech
  dnsNames:
    - kiri.tech
    - www.kiri.tech
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kiri.tech
          - www.kiri.tech
